export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';

export const SELECT_QUESTION_SUCCESS = 'SELECT_QUESTION_SUCCESS';
export const INSERT_QUESTION_SUCCESS = 'INSERT_QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';





